version: '3.1'

services:

  wordpress:
    container_name: wp
    depends_on:
     - db
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./src:/var/www/html
      - ./src/wp-content:/var/www/html/wp-content

  db:
    container_name: db
    image: mysql:5.7
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
volumes:
  dbdata:
  wp-content: